// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: P4-squareLine

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void LedON(lv_event_t * e);
void LedOn(lv_event_t * e);
void LedOff(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
