// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: P4-squareLine

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_ButtonON = NULL;
lv_obj_t * ui_LabelON = NULL;
lv_obj_t * ui_ButtonOFF = NULL;
lv_obj_t * ui_LabelOFF = NULL;
// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        LedON(e);
    }
}

void ui_event_ButtonON(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        LedOn(e);
    }
}

void ui_event_ButtonOFF(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        LedOff(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image1, &ui_img_table_lamp400_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 400
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 400
    lv_obj_set_x(ui_Image1, -202);
    lv_obj_set_y(ui_Image1, 18);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonON = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonON, 280);
    lv_obj_set_height(ui_ButtonON, 130);
    lv_obj_set_x(ui_ButtonON, 220);
    lv_obj_set_y(ui_ButtonON, -110);
    lv_obj_set_align(ui_ButtonON, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonON, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonON, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonON, lv_color_hex(0xFABB39), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelON = lv_label_create(ui_ButtonON);
    lv_obj_set_width(ui_LabelON, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelON, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelON, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelON, "ON");
    lv_obj_set_style_text_color(ui_LabelON, lv_color_hex(0xE64429), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelON, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonOFF = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonOFF, 280);
    lv_obj_set_height(ui_ButtonOFF, 130);
    lv_obj_set_x(ui_ButtonOFF, 220);
    lv_obj_set_y(ui_ButtonOFF, 110);
    lv_obj_set_align(ui_ButtonOFF, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonOFF, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonOFF, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonOFF, lv_color_hex(0xFABB39), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonOFF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOFF = lv_label_create(ui_ButtonOFF);
    lv_obj_set_width(ui_LabelOFF, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOFF, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelOFF, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOFF, "OFF");
    lv_obj_set_style_text_color(ui_LabelOFF, lv_color_hex(0xE64429), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOFF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOFF, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonON, ui_event_ButtonON, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonOFF, ui_event_ButtonOFF, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Image1 = NULL;
    ui_ButtonON = NULL;
    ui_LabelON = NULL;
    ui_ButtonOFF = NULL;
    ui_LabelOFF = NULL;

}
