// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: P4-squareLine

#include "ui.h"
#include "bsp_extra.h"

void LedON(lv_event_t * e)
{
	// Your code here
}

void LedOn(lv_event_t * e)
{
	// Your code here
	gpio_extra_set_level(true);
}

void LedOff(lv_event_t * e)
{
	// Your code here
	gpio_extra_set_level(false);
}
