// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: P4-squareLine

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern void ui_event_ButtonON(lv_event_t * e);
extern lv_obj_t * ui_ButtonON;
extern lv_obj_t * ui_LabelON;
extern void ui_event_ButtonOFF(lv_event_t * e);
extern lv_obj_t * ui_ButtonOFF;
extern lv_obj_t * ui_LabelOFF;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

